on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to stand up FusionAuth
    steps:
      - uses: actions/checkout@v2
      - name: Echo something
        run: echo "hi"
      - name: CWD
        run: pwd
      - name: sleep
        run: sleep 15
      - name: docker container
        run: docker container ls
      - name: docker networks
        run: docker network ls
      - name: Curl localhost
        run: curl -vv http://localhost:9011/api/status
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      fusionauth:
        # Docker Hub image
        image: fusionauth/fusionauth-app:latest
        ports:
          - 9011:9011
        #options: >-
          #--health-cmd 'curl --connect-timeout 2 -s -o /dev/null -w "%{http_code}" http://localhost:9011/api/status || exit 1;' 
          #--health-interval 10s
          #--health-timeout 5s
          #--health-retries 10
        env:
          DATABASE_URL: jdbc:postgresql://postgres:5432/fusionauth
          DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
          DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
          DATABASE_USERNAME: test
          DATABASE_PASSWORD: test123
          FUSIONAUTH_APP_MEMORY: 512M
          FUSIONAUTH_APP_RUNTIME_MODE: development
          FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
          SEARCH_TYPE: database
        volumes:
          - /home/runner/work/docker-github-workflow/docker-github-workflow/kickstart:/usr/local/fusionauth/kickstart
      
