on: [push]

# see https://stackoverflow.com/questions/57115520/can-i-have-multiple-github-actions-workflow-files for details on how to tweak this

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to stand up FusionAuth
    env:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: postgres2
      FUSIONAUTH_VERSION: 1.29.0
    steps:
      - uses: actions/checkout@v2
      - uses: mooreds/docker-github-action@v1.0.2
      - name: Sleep
        run: sleep 31
      #- name: up
        #run: docker-compose up -d
      #- name: Sleep
        #run: sleep 30
      #- name: Interact with FusionAuth
        #run: "curl -vv -H 'Authorization: 4737ea8520bd454caabb7cb3d36e14bc1832c0d3f70a4189b82598670f11b1bd' http://localhost:9011/api/tenant |grep allowEmailChangeWhenGated"
      #- name: Shut down FusionAuth
        #run: docker-compose down
